language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'

install:
- pip install -r requirements.txt
- pip install .

script: nosetests

deploy:
  provider: pypi
  user: tradel
  password:
    secure: "YUWD7Lsggc6lQoaC0mFWElu8Ea80Ej78mC6kTCdzR6O9Hmk+fh02YR2+nq6I4tMCAMILLjj6vHVaeSp6/Zx4GTe0O9XJxl+afuA6LarU6zN18Y6FOvK+9G8JRelESDice56IGZyYCwLXlSgihZ6tHTYXRfVT04i2dR7O5KM0uOE="
  distributions: sdist bdist_wheel
  on:
    tags: true
